spring.application.name=Benny_Bach_Coupons_Project_SpringV
spring.datasource.url=jdbc:mysql://localhost:3306/couponsdb_spring
spring.datasource.username=root
spring.datasource.password=3674
spring.jpa.hibernate.ddl-auto=update
